name: openim_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.49+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_screenutil: 5.5.4
  get: 4.6.5
  shared_preferences: 2.0.15
  path_provider: 2.0.11
  sprintf: 7.0.0
  rxdart: 0.27.5
  pin_code_fields: 7.3.0
  image_picker: 0.8.4+9
  dio: 4.0.6
  azlistview: 2.0.0
  lpinyin: 2.0.3
#  country_code_picker: 2.0.2
  country_picker: 2.0.19
  image_gallery_saver: 1.7.1
  flutter_easyloading: 3.0.5
  wechat_assets_picker: 7.3.1
  wechat_camera_picker: 3.2.0+1
  file_picker: 4.4.0
  open_file: 3.2.1
  permission_handler: 10.1.0
  mime_type: 1.0.0
  uuid: 3.0.6
  cached_network_image: 3.2.2
  lottie: 1.4.3
  qr_flutter: 4.0.0
  image_cropper: 2.0.3
  dotted_decoration: 2.0.0
  package_info_plus: 1.4.0
  search_keyword_text: ^0.0.2
  qr_code_scanner: 1.0.0
  pretty_dio_logger: 1.2.0-beta-1
  logger: 1.1.0
  animated_text_kit: 4.2.1
  flutter_local_notifications: 9.3.2
  flutter_app_badger: 1.3.0
  crypto: 3.0.1
  pull_to_refresh: 2.0.0
  url_launcher: 6.0.20
  sp_util: 2.0.3
  common_utils: 2.1.0
  uri_to_file: 0.2.0
  map_launcher: 2.2.1+1
  flutter_map: 0.14.0
  flutter_spinkit: 5.1.0
  percent_indicator: 4.2.2
  flutter_image_compress: 1.1.3
  app_installer: 1.1.0
  r_scan: 0.1.6+1
  collection: 1.17.0
  flutter_bugly: 0.4.4
  tencent_cos: 1.0.5
  flutter_cupertino_datetime_picker: 3.0.0
  device_info_plus: 6.0.0
  dart_date: ^1.1.1
  getuiflut: 0.2.14
  # flutter_openim_widget: 2.3.5+3
  flutter_openim_widget:
    git:
      url: https://github.com/hrxiang/flutter_openim_widget.git
      ref: 2.3.5+3
  agora_rtc_engine: ^6.2.0
  # permission_handler: ^10.2.0
  agora_chat_sdk: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  scrollable_positioned_list: 0.3.2
  #  visibility_detector: ^0.3.3
  xml: 6.0.1
  camera_android: 0.9.7+1
  camera_avfoundation: 0.9.7+1
  emoji_picker_flutter: 1.4.0
  ffi: 2.0.1
  pull_to_refresh: ^2.0.0
  # pull_to_refresh:
  #   git:
  #     url: https://github.com/miquelbeltran/flutter_pulltorefresh
  #     ref: master

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
