name: CI
on:
  push:
    branches: [ master , main]

jobs:
  build-apk:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "17"

      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
          flutter-version: "3.7.3"

      - name: Debug print ANDROID_NDK_HOME
        run: echo $ANDROID_NDK_HOME
        
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            Pods
            ${{ env.ANDROID_NDK_HOME }}
          key: |
            ${{runner.OS}}-gradle-caches-${{ hashFiles('pubspec.lock') }}
            ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            ${{ runner.os }}-ndk-${{ hashFiles(env.ANDROID_NDK_HOME) }}
          restore-keys: |
            ${{ runner.os }}-pods-
            ${{ runner.os }}-gradle-

      # - name: Install NDK
      #   run: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669" "cmake;3.10.2.4988404"

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Build apk
        if: ${{ runner.os == 'Linux' }}
        run: flutter build apk

      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: qimudi.${{ github.sha }}.android
          path: build/app/outputs/flutter-apk/app-release.apk
        
  build-ios:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: "17"

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            Pods
            ${{ env.ANDROID_NDK_HOME }}
          key: |
            ${{runner.OS}}-gradle-caches-${{ hashFiles('pubspec.lock') }}
            ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            ${{ runner.os }}-ndk-${{ hashFiles(env.ANDROID_NDK_HOME) }}
          restore-keys: |
            ${{ runner.os }}-pods-
            ${{ runner.os }}-gradle-

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: qimudi.${{ github.sha }}.ios
          path: Payload.ipa
